# netlify.toml

# Build settings for the frontend (React.js)
[build]
  command = "npm run build"  # Specify the build command for your React app
  publish = "client/build"   # Specify the build output directory

# Build settings for the backend (Node.js)
[[plugins]]
  package = "@netlify/plugin-functions"  # Use the Netlify Functions plugin
  [plugins.inputs]
    functions = "index.js"    # Specify the directory containing your serverless functions

# Optional: Redirects or other settings specific to your project

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

